from .default_preferences import shortcut_keys, visual_preferences
from .load_preferences import save_preferences, load_preferences
from .shortcuts_widget import ShortcutsWidget
from .visual_preferences_widget import VisualPreferencesWidget
